#!/bin/bash

# List of programs

# vscode
# go
# python
# node
# docker
# docker-compose
# postman
# chrome
# discord
# telegram
# tree
# htop
# tmux


# Configs

# tmux
# vscode
# vim
# git
# bashrc (paths, prompt)








